version: "3.9"

services:
    web:
        container_name: web
        build: .
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
        depends_on:
            - db
        command: sh -c "sleep 10 && python seeds.py && flask run --host=0.0.0.0 --port=5000"
    db:
        container_name: db
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=library
        volumes:
            - ./data:/var/lib/postgresql/data

volumes:
    db:
